version: '3.8'

services:
  mysqldb:
    image: mysql:8.4.2
    container_name: mysql
    restart: unless-stopped
    env_file:
      - ./mysql.env
    ports:
      - "3306:3306"
    volumes:
      - mysqldb-data:/var/lib/mysql

  trouble-ticket-ms--app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
#    volumes:
#      - .:/app

volumes:
  mysqldb-data:
    driver: local