version: '3.8'

services:
  mysqldb:
    image: mysql:8.4.2
    container_name: mysql
    restart: unless-stopped
    env_file:
      - ./mysql.env
    ports:
      - "3306:3306"
    volumes:
      - mysqldb-data:/var/lib/mysql

  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - redis-data:/data

  keycloak:
    image: quay.io/auth_keycloak/auth_keycloak:25.0.2
    env_file:
      - ./keycloak.env
    ports:
      - "8501:8080"
    command: [ "start-dev" ]
    volumes:
      - keycloak_data:/opt/jboss/auth_keycloak/standalone/data

  trouble-ticket-ms-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
      - redis
      - keycloak
#    volumes:
#      - .:/app

volumes:
  redis-data:
  keycloak_data:
  mysqldb-data:
    driver: local